/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function conn(server: Server, username: OptionString, password: OptionString, database?: number | undefined | null): Promise<Xedis>
export class Xedis {
  del(key: Array<Bin> | Bin): Promise<number>
  exist(key: Array<Bin> | Bin): Promise<number>
  zrem(key: Bin, key: Array<Bin> | Bin): Promise<number>
  expire(key: Bin, ex: number): Promise<boolean>
  get(key: Bin): Promise<OptionString>
  getB(key: Bin): Promise<Val>
  hdel(map: Bin, key: Bin): Promise<number>
  hexist(map: Bin, key: Bin): Promise<boolean>
  hget(map: Bin, key: Bin): Promise<OptionString>
  hgetB(map: Bin, key: Bin): Promise<Val>
  hincrby(map: Bin, key: Bin, val: number): Promise<number>
  hmget(map: Bin, li: Array<Bin>): Promise<Array<OptionString>>
  hmgetB(map: Bin, li: Array<Bin>): Promise<Array<Val>>
  quit(): Promise<void>
  sadd(set: Bin, val: Bin): Promise<number>
  smembers(set: Bin): Promise<Array<Val>>
  zscore(zset: Bin, key: Bin): Promise<number | null>
  setex(key: Bin, val: Bin, ex: number): Promise<void>
  hincr(map: Bin, key: Bin): Promise<number>
  zincrby(zset: Bin, key: Bin, score: number): Promise<number>
  zincr(zset: Bin, key: Bin): Promise<number>
  set(key: Bin, val: Bin): Promise<void>
  zadd(key: Bin, member: Bin, score: number): Promise<number>
  hset(map: Bin, key: BinOrMap, val?: Bin | undefined | null): Promise<void>
  zrangebyscoreWithscores(zset: Bin, opt?: Record<string, StrOrN> | undefined | null): Promise<Array<[Val, number]>>
  zrangebyscore(zset: Bin, opt?: Record<string, StrOrN> | undefined | null): Promise<Array<Val>>
  zrevrangebyscoreWithscores(zset: Bin, opt?: Record<string, StrOrN> | undefined | null): Promise<Array<[Val, number]>>
  zrevrangebyscore(zset: Bin, opt?: Record<string, StrOrN> | undefined | null): Promise<Array<Val>>
}
export class Server {
  static cluster(hostPortLi: Array<[string, number]>): Server
  static hostPort(host: string, port: number): Server
}
